#+TITLE: Dockerfile for SuperNEMO software
#+DATE: 2017/12/20
#+AUTHOR: Xavier Garrido

In these directories, you will find several =Dockerfiles= to build SuperNEMO software. The
installation process is done from scratch using different docker images (presently only ubuntu 16.04
is supported).

The next section shows you how to build and to run the docker image.

* Building the image

You can first checkout this repository
#+BEGIN_SRC shell
  $ git clone https://github.com/xgarrido/dockerfiles
#+END_SRC
and then run the next command from your local repository
#+BEGIN_SRC shell
  $ cd snemo/ubuntu/16.04
  $ docker build -t snemo/ubuntu16.04 .
#+END_SRC

You can also build the =docker= image without checking out the github repository by doing
#+BEGIN_SRC shell
  $ docker build -t snemo/ubuntu16.04 "github.com/xgarrido/dockerfiles#:snemo/ubuntu/16.04"
#+END_SRC

The =-t= flag set the name of the image and will be used when running your container.

Every time you use the =build= command, =docker= uses a cached version to decrease the start
time. If you want to restart from scratch (for instance to update a remote git repository within
your =docker= image), you should use the =--no-cache= option in the =docker build= command line. All the
options of =docker build= command can be found [[https://docs.docker.com/engine/reference/commandline/build/][here]].

* Running the image

Given that the =build= operation succeeds, you can interactively run your image by doing
#+BEGIN_SRC shell
  $ docker run --rm -it snemo/ubuntu1604:latest /bin/zsh
#+END_SRC
You will be prompted as =snemo= user to a =zsh= terminal; SuperNEMO software is installed in
=/home/snemo/software=. The =--rm= ensures everything gets cleaned when stopping the image.

To forward =DISPLAY=, you should add the following options
#+BEGIN_SRC shell
  $ docker run -e DISPLAY=$DISPLAY \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       --rm -it snemo/ubuntu1604:latest /bin/zsh
#+END_SRC
